services:
  - type: web
    name: portfolio-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn portfolio_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: django-insecure--#8km&ldq82pf5%^6#35t$m@t*-1i*3@=2e)upby!3@&cx7rj$
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: portfoliobackend-5mtm.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,https://portfoliofrontend-tau.vercel.app
      # Add your Cloudinary credentials here
      # - key: CLOUDINARY_CLOUD_NAME
      #   value: your_cloud_name
      # - key: CLOUDINARY_API_KEY
      #   value: your_api_key
      # - key: CLOUDINARY_API_SECRET
      #   value: your_api_secret
      # Add your PostgreSQL database URL here
      # - key: DATABASE_URL
      #   value: your_postgres_database_url
