# Generated by Django 5.2 on 2025-08-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resume_remove_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Python', 'Python Apps'), ('Full-Stack', 'Full-Stack Apps'), ('Graphic Design', 'Graphic Design')], default='Full-Stack', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
