# Generated by Django 5.2 on 2025-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_convert_to_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Python', 'Python Apps'), ('Full-Stack', 'Full-Stack Apps'), ('Graphic Design', 'Graphic Design'), ('UI/UX', 'UI/UX Projects')], default='Full-Stack', max_length=50),
        ),
    ]
